
DB_NAME = 'data_name'
SQLALCHEMY_DATABASE_URI = 'database_uri'

SECRET_KEY = 'thisisasecret'
CSRF_ENABLED = True
USER_ENABLE_EMAIL = False
USER_ENABLE_REGISTER = False
USER_APP_NAME = "app name"
SQLALCHEMY_TRACK_MODIFICATIONS = False
