name: Redeploy

on:
  push:
    branches: [ main ]
  release:
    types:
      - published


jobs:

  redeploy:
      name: Redeploy - Webhook call
      runs-on: ubuntu-latest
      steps:
        - name: Send Webhook Request
          uses: joelwmale/webhook-action@master
          env:
            WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
            data: "{ 'myField': 'myFieldValue'}" # add authentication for webhook
